language: ruby
sudo: required
cache:
  directories:
    - bundler

rvm:
  - 2.5.1

addons:
  chrome: stable

services:
  - mysql
  - postgresql

env:
  - DB=mysql
  - DB=pg

matrix:
  allow_failures:
    - env: DB=pg

before_install:
  - 'cp "config.yml.${DB}.travis" "config.yml"'

before_script:
  - 'if [ "$DB" = "pg" ]; then psql -c "create database myapp;" -U postgres; fi'
  - bundle exec rake dummy:setup

script: xvfb-run bundle exec rake ci
