dist: bionic
language: ruby
cache: bundler
rvm:
  - 2.6

addons:
  apt:
    packages:
      - chromium-browser
      - chromium-chromedriver

services:
  - mysql

before_install:
  - sudo rm /usr/bin/google-chrome

install:
  - cp config.yml.mysql.travis config.yml
  - bundle install
  - bundle exec rake dummy:setup

script:
  - xvfb-run bundle exec rake ci
